Autoclosure: typechecking and code generation (1)
hylo-lang/hylo pull request #1151
Opened 2023-11-19 18:35 UTC by lucteo

Part of the implementation needed for #1036.

This doesn't properly deal with lambdas that have non-void environments.

2023-12-01 22:24 UTC, kyouko-taiga commented on Sources/Core/Types/ParameterType.swift
> +  /// Indicates if the parameter is marked as autoclosure.
```suggestion
  /// `true` iff the parameter is an autoclosure.
```

2023-12-01 22:25 UTC, kyouko-taiga commented on Sources/FrontEnd/TypeChecking/ConstraintSystem.swift
> +      if p.isAutoclosure {
I think the whole clause deserves to be in a separate function, so that we can give it a comment.

2023-12-01 22:27 UTC, kyouko-taiga commented on Tests/EndToEndTests/TestCases/Autoclosure.hylo
> +  // Test with generics and non-void environments.
```suggestion
  // TODO: Test with generics and non-void environments.
```

2023-12-01 22:29 UTC, kyouko-taiga requested changes
Nice work, really!

I think the handling of auto closures in the constraint solver deserves to be in its own function.

2023-12-05 18:10 UTC, lucteo commented on Sources/Core/AST/Decl/SynthesizedFunctionDecl.swift
> +    guard !type.captures.isEmpty else { return [] }
For the synthesised autoclosure, we may have no captures. If that's the case, then the code below would fail (there is no receiver). This is similar to how we are testing inside the `description` property.

2023-12-05 18:11 UTC, merged