Rotate robustness
hylo-lang/hylo pull request #1279
Opened 2024-01-05 03:29 UTC by dabrahams

This PR adds a much more complete test of Hylo's rotate and makes it handle one important case that used to cause an assertion.

Except for not returning the new pivot, it actually does work!  So I'm sorry I doubted it (@kyouko-taiga). Amazingly, the swift implementation it was derived from failed [this test](https://github.com/hylo-lang/hylo/blob/045f1bb3f3313b532bb67dfc4285cf2fdb6dfce6/Tests/UtilsTests/CollectionExtensionsTests.swift#L68-L89).

As a student of rotate, I was expecting to see nested loops, which I have in my implementation.  But it's been too long since I worked on that algorithm, so I had forgotten the purpose of that nesting; I should have remembered that since it's O(N)  that nesting isn't strictly necessary; it just avoids a bunch of tests/branches.  

The comments in the current implementation still don't make sense to me, so I don't understand how it works and thus I can't quite figure out how to get it to return the new pivot, so I will submit a separate PR that replaces the implementation.

2024-01-05 05:34 UTC, sean-parent commented on StandardLibrary/Sources/Core/MutableCollection.hylo
> +  /// originally at `start_position()` (if any).
What if there wasn't any? 
```suggestion
originally at the `start_position()`, if any, otherwise end_position().
```

2024-01-05 05:41 UTC, sean-parent requested changes
The code looks good. The contract needs a little work. I suggested an improvement, but I think it could be further improved.

2024-01-05 08:36 UTC, kyouko-taiga commented on Tests/LibraryTests/TestCases/MutableCollectionTests.hylo
> +fun appendCount(up_to limit: Int, to a: inout Array<Int>) {
```suggestion
fun append_count(up_to limit: Int, to a: inout Array<Int>) {
```

2024-01-05 08:37 UTC, kyouko-taiga commented on Tests/LibraryTests/TestCases/MutableCollectionTests.hylo
> +    appendCount(up_to: N, to: &a)
```suggestion
    append_count(up_to: N, to: &a)
```

2024-01-05 08:54 UTC, kyouko-taiga commented
> Amazingly, the swift implementation it was derived from failed this test.

Sadly I can't find back the sources from which I took inspiration to write the my Swift implementation. I didn't understand that code very well, though, so the Hylo one was my attempt at simplifying it. It's interesting that this exercise didn't port the bug from the original!

Anyway, thanks for writing this better-researched version.

2024-01-06 01:18 UTC, dabrahams commented on StandardLibrary/Sources/Core/MutableCollection.hylo
> +  /// originally at `start_position()` (if any).
@sean-parent If I wanted to cover all the cases, I'd have to deal with the other two “(if any)”s.  The full semantics of the function are precisely described by the summary and this paragraph is supplemental; it's designed to help people visualize what happens, so I thought it better to deal with those edge cases by explicitly leaving them out, lest the language get too dense to understand.  Unless you can tell me why this one “(if any)” is special, it seems to me my choices should be:

1. deal with all the (if any)s in the same way you've suggested for the third one.
2. leave the paragraph alone.
3. strike the paragraph.

WDYT?

2024-01-06 01:21 UTC, dabrahams commented on Tests/LibraryTests/TestCases/MutableCollectionTests.hylo
> +fun appendCount(up_to limit: Int, to a: inout Array<Int>) {
Oh, good catch!  Old habits die hard (also when switching between codebases).

2024-01-06 08:29 UTC, sean-parent commented on StandardLibrary/Sources/Core/MutableCollection.hylo
> +  /// originally at `start_position()` (if any).
This "if any" is different in that it is describing the result - so I don't think you can leave it out. It is precise in the paragraph above, so you could just strike it.

2024-01-06 16:56 UTC, dabrahams commented on StandardLibrary/Sources/Core/MutableCollection.hylo
> +  /// originally at `start_position()` (if any).
Struve the (if any) or the whole paragraph?

2024-01-06 19:59 UTC, dabrahams commented on StandardLibrary/Sources/Core/MutableCollection.hylo
> +  /// originally at `start_position()` (if any).
Another alternative would be to open the supplemental section with, “Except for trivial cases where `p` is at either end of `self`,…”

2024-01-06 21:56 UTC, sean-parent commented on StandardLibrary/Sources/Core/MutableCollection.hylo
> +  /// originally at `start_position()` (if any).
I would either strike the sentence (don't have supplement text about the result) or strike the paragraph. I'm not sure it adds much. Even the "except for trivial cases..." phrasing needs to state what is returned in the trivial cases. The first "if any" is fine because, in that case, there is no effect, which is what "if any" implies.

2024-01-07 02:16 UTC, merged