Support versioning the compiler
hylo-lang/hylo pull request #1320
Opened 2024-01-19 11:39 UTC by peter-evans

Closes https://github.com/hylo-lang/hylo/issues/1120

- Adds a `-V` / `--version` flag to the compiler.
- Adds a script to set the compiler version. This is mainly for use in CI so that tags can be set as the version before building. The script can also be called during local development to set the version to a git hash. It could help when triaging issues to understand the commit the compiler was built at. This was the motivation for the original [issue](https://github.com/hylo-lang/hylo/issues/1120).
- Updates CI to set the version of the compiler either to a tag (if a `v` prefixed tag is pushed), or the git hash in all other cases.

2024-01-19 11:51 UTC, peter-evans commented on .github/workflows/build-and-test.yml
> +      run: .build/debug/hc --version
We can remove these output steps if you don't want them. I was using them to check the version was set correctly, but they might be useful, anyway.

2024-01-19 11:51 UTC, peter-evans commented on Sources/Driver/Driver.swift
> +  private var inputs: [URL] = []
This change was necessary to allow commands that don't include `inputs`. Without this, `hc --version` throws during parsing the arguments because `inputs` is missing.

2024-01-19 11:51 UTC, peter-evans commented on Sources/Driver/Driver.swift
> +    }
I added this custom validation because `inputs` now has a default and is optional during argument parsing.

The `ValidationErrorWithHelp` custom message mimics the output when validation fails during parsing.

2024-01-19 11:51 UTC, peter-evans commented on Tests/DriverTests/DriverTests.swift
> +    XCTAssertThrowsError(try cli.execute())
Updated this test because now validation fails during execution, not parsing.

2024-01-19 11:51 UTC, peter-evans commented on Sources/Driver/Driver.swift
> +      standardError.write("\(hcVersion)\n")
All output seems to be going to standard error, but perhaps in this case it should be standard out?

2024-01-19 11:51 UTC, peter-evans commented on Tools/set-hc-version.sh
> +git update-index --assume-unchanged $VERSION_FILE
This tells git to assume the file is unchanged. It's just to try and prevent it from being committed accidentally.

2024-01-19 12:07 UTC, peter-evans commented
You'll notice if you look at the build log that the version is currently `836ec749b5f023a2425d006cff8985b438a8b947`, which doesn't match any of the commits in the PR. The reason for this is that `pull_request` events create a temporary merge commit on the runner. So what is actually being tested in `pull_request` events is a temporary local commit on the runner, which mimics the state of git after this branch is merged to `main`.

There is no problem here. When CI runs on merge to `main` it will correctly pick up the git hash of the `HEAD` of `main`.

2024-01-19 14:13 UTC, kyouko-taiga commented on Sources/Driver/Driver.swift
> +      var message: String
```suggestion

      var message: String
```

2024-01-19 14:13 UTC, kyouko-taiga commented on Sources/Driver/Driver.swift
> +      }
```suggestion
      }

```

2024-01-19 14:14 UTC, kyouko-taiga commented on Sources/Driver/Driver.swift
> +        throw ValidationErrorWithHelp("Missing expected argument '<inputs> ...'")
```suggestion
      throw ValidationErrorWithHelp("Missing expected argument '<inputs> ...'")
```

2024-01-19 14:15 UTC, kyouko-taiga requested changes
LGTM. Suggested changes are only about style. Perhaps you should also try running swift-format just to be sure.

2024-01-19 14:31 UTC, peter-evans commented on Sources/Driver/Driver.swift
> +      var message: String
https://github.com/hylo-lang/hylo/pull/1320/commits/06ef911af8ee735eb294839f1aa5494768c0a841

2024-01-19 14:31 UTC, peter-evans commented on Sources/Driver/Driver.swift
> +      }
https://github.com/hylo-lang/hylo/pull/1320/commits/06ef911af8ee735eb294839f1aa5494768c0a841

2024-01-19 14:31 UTC, peter-evans commented on Sources/Driver/Driver.swift
> +        throw ValidationErrorWithHelp("Missing expected argument '<inputs> ...'")
https://github.com/hylo-lang/hylo/pull/1320/commits/06ef911af8ee735eb294839f1aa5494768c0a841

2024-01-22 07:46 UTC, kyouko-taiga approved these changes

2024-01-22 07:46 UTC, kyouko-taiga commented
Great work! Thanks a lot.

2024-01-22 07:46 UTC, merged