Parse attribute arguments as expressions
hylo-lang/hylo pull request #1336
Opened 2024-01-26 17:25 UTC by peter-evans

Closes https://github.com/hylo-lang/hylo/issues/76

---

Commit: https://github.com/hylo-lang/hylo/commit/b9cd50c4f3012fc939b9ffe93b521163a263aaab
- Parses attribute arguments as expressions (`AnyExprID`).
- Parses `@autoclosure` as a special case without arguments in `parseParameterTypeExpr` due to [this issue](https://github.com/hylo-lang/hylo/issues/76#issuecomment-1898820655).
- Removes `error(attributeTakesNoArgument...` and related diagnostic test because they are no longer used.
- Extracts `foreignName` and `externalName` from `FunctionDecl` into functions in the AST

Commit: https://github.com/hylo-lang/hylo/commit/cc3047c2d42b9b3dd8c17d5141d40b14000b077b
- Adds a `BundledNode` extension for `foreignName` on `FunctionDecl`

Commit: https://github.com/hylo-lang/hylo/commit/136f946aa77f5b8e942d2b38eca418413cc25818
- Adds a `BundledNode` extension for `externalName` on `FunctionDecl`

2024-01-28 09:43 UTC, kyouko-taiga commented on Sources/FrontEnd/BundledNode+Extensions.swift
> +extension BundledNode where T == FunctionDecl.ID, P == TypedProgram {
```suggestion
extension BundledNode where T == FunctionDecl.ID {
```
I think the property lives in the AST, so you should be able to compute it with any kind of program. Same for `externalName`

2024-01-28 09:45 UTC, kyouko-taiga commented on Sources/FrontEnd/BundledNode+Extensions.swift
> +extension BundledNode where T == FunctionDecl.ID, P == TypedProgram {
Ah, now I see that you defined property maps for those attributes.

2024-01-28 09:48 UTC, kyouko-taiga commented on Sources/FrontEnd/TypedProgram.swift
> +  public internal(set) var externalName: [FunctionDecl.ID: String] = [:]
It's a good idea to add property maps but I think we should combine these two properties into some kind of abstraction describing all the attributes of the function that have an impact on its API. For instance, we'll soon add information about inlining too.

2024-01-28 09:51 UTC, kyouko-taiga requested changes
Great work. I have only one comment about the property maps you added to `TypedProgram`.

2024-01-30 17:00 UTC, peter-evans commented on Sources/FrontEnd/TypedProgram.swift
> +  public internal(set) var externalName: [FunctionDecl.ID: String] = [:]
Please see this commit: https://github.com/hylo-lang/hylo/pull/1336/commits/b6614874b934384688ef1571cb0431bf17fddc11

I'm not sure if `FunctionAttributes` is the correct name for the abstraction, or even if it's in the right place in the code base.

2024-03-19 10:51 UTC, kyouko-taiga approved these changes

2024-03-19 12:14 UTC, merged