Refactor function reference creation
hylo-lang/hylo pull request #1344
Opened 2024-02-02 17:24 UTC by peter-evans

Closes https://github.com/hylo-lang/hylo/issues/965

I took a shot at the linked issue and tried to refactor creation of references. I didn't see an easy way to refactor it significantly, but perhaps this is a bit of an improvement. Sorry if it's way off base. 😅

2024-02-02 17:37 UTC, peter-evans commented on Sources/IR/Analysis/Module+FunctionReferencing.swift
> +      return FunctionReference(to: f, in: &copy, specializedBy: specialization, in: scopeOfUse)
The constructor of `FunctionReference` requiring `inout Module` for `AnyDeclID` makes it a little tricky to refactor. To simplify further perhaps it's worth extracting `let f = module.demandDeclaration(lowering: d)!` out and making callers convert to `Function.ID` before reference creation. 🤷‍♂️ 

```swift
public struct FunctionReference: Constant, Hashable {
...

  public init(
    to d: AnyDeclID, in module: inout Module,
    specializedBy specialization: GenericArguments, in scopeOfUse: AnyScopeID
  ) {
    let f = module.demandDeclaration(lowering: d)!
    self.init(to: f, in: module, specializedBy: specialization, in: scopeOfUse)
  }
}
```

2024-02-12 23:07 UTC, kyouko-taiga commented on Sources/IR/Analysis/Module+FunctionReferencing.swift
> +      return FunctionReference(to: f, in: &copy, specializedBy: specialization, in: scopeOfUse)
Giving a copy of `self` to method is the wrong approach. we do care about the mutation of the module, which is why it's taken inout. The mutation is necessary because it is possible the reference is made to a function whose IR hasn't been declared in the module yet.

2024-02-12 23:17 UTC, kyouko-taiga commented on Sources/IR/Analysis/Module+FunctionReferencing.swift
> +    if let f = f as? Function.ID {
We should stay away from dynamic type tests on types. That makes the signature of the method harder to read because `T` is now underspecified. Even with the proper documentation, we'd be losing the benefits of static type checking, as there's nothing to catch me at compile-time if I pass an `Int` to `reference(to:specialization:in:)`.

I would write two distinct methods here, as their implementations share no code. In situations where code is shared, I would consider defining a protocol describing shared requirements. But in any case I would start with distinct implementations.

2024-02-12 23:19 UTC, kyouko-taiga requested changes
Most call sites look better, so I think this PR goes in the right direction. However I think `reference(to:specialization:in:)` requires more work.

We have to make sure module mutations are not lost. Further I would write different implementations to avoid dynamic type tests on an unconstrained generic parameter.

2024-06-13 10:07 UTC, peter-evans commented
I don't have time to work on this further at the moment so I'll close for now. If anyone wants to pick it up, feel free. I'll try to swing back and take a look again when I have time.

2024-06-13 10:07 UTC, closed without merging