Escaping spawn
hylo-lang/hylo pull request #1408
Opened 2024-03-24 21:19 UTC by lucteo

Add support for `spawn` in which the `await` is made in a different scope.
In this case, the frame object needs to be allocated on the heap.

2024-03-28 17:42 UTC, kyouko-taiga commented on StandardLibrary/Sources/Concurrency/Future.hylo
> +  public fun manual_init(_ f: sink [E]() -> Int) set {
Why did you call it `manual_init`. You can call `init` "manually" as a static method if you want:

```
type A: Deinitializable {
  public init(x: Int) {}
}

public fun main() {
  var a: A
  A.`init`(self: &a, x: 1)
}
```

2024-03-28 17:42 UTC, kyouko-taiga commented on StandardLibrary/Sources/Concurrency/Future.hylo
> +    &self.frame = alloc_frame(f)
```suggestion
    &self.frame = allocate_frame(f)
```

2024-03-28 17:45 UTC, kyouko-taiga commented on StandardLibrary/Sources/Concurrency/Future.hylo
> +  private static fun alloc_frame(_ f: sink [E]() -> Int) -> PointerToMutable<SpawnFrame<E>> {
Let's try to document every function we write in the standard library, even if they are private.

2024-03-28 17:47 UTC, kyouko-taiga requested changes
Nice PR, thanks. I'm not convinced that defining an initializer with a custom name is justified, but otherwise it looks good. My other comments are mostly about style.

2024-03-29 20:01 UTC, lucteo commented on StandardLibrary/Sources/Concurrency/Future.hylo
> +  public fun manual_init(_ f: sink [E]() -> Int) set {
Fixed. Thank you, I did not know that.

2024-03-29 20:02 UTC, lucteo commented on StandardLibrary/Sources/Concurrency/Future.hylo
> +    &self.frame = alloc_frame(f)
Moved it as internal method of `SpawnFrame`.

2024-03-29 20:02 UTC, lucteo commented on StandardLibrary/Sources/Concurrency/Future.hylo
> +  private static fun alloc_frame(_ f: sink [E]() -> Int) -> PointerToMutable<SpawnFrame<E>> {
Fixed. Thank you.

2024-03-30 13:30 UTC, kyouko-taiga approved these changes
LGTM

2024-03-30 16:12 UTC, merged