Add && and || operators to compile-time compilation conditions (#1358)
hylo-lang/hylo pull request #1410
Opened 2024-03-26 16:35 UTC by Metalymph

This commit allow the use of something like this:
```
public fun main() {
    #if arch(arm64) && false
        print("False for sure!")
    #elseif os(windows) || os(linux)
        print("Win or linux")
    #elseif arch(x86_64) || arch(arm64) && !false
        let message = "Arm64 or x86_64 (multiple operators condition)"
    #else
        print("unreachable")
    #endif
    print(message)
}
```

2024-03-28 07:22 UTC, kyouko-taiga commented on Sources/CodeGen/LLVM/LLVMProgram.swift
> +  public func write(_ type: SwiftyLLVM.CodeGenerationResultType, to directory: URL) throws -> [URL]
This change seems unnecessary. Why did it happen?

2024-03-28 07:24 UTC, kyouko-taiga commented on Sources/CodeGen/LLVM/LLVMProgram.swift
> +  public func write(_ type: SwiftyLLVM.CodeGenerationResultType, to directory: URL) throws -> [URL]
Ah, I guess it's swift-format doing its job after `LLVM` has become `SwiftyLLVM`.

2024-03-28 07:25 UTC, kyouko-taiga commented on Sources/CodeGen/LLVM/LLVMProgram.swift
> +  {
```suggestion
  public func write(
    _ type: SwiftyLLVM.CodeGenerationResultType, to directory: URL
  ) throws -> [URL] {
```

It is unfortunate that swift-format doesn't apply this style (although it accepts it) but that's the one used consistently in the code base for parameter lists that exceed the character limit.

2024-03-28 07:26 UTC, kyouko-taiga commented on Sources/CodeGen/LLVM/TypeLowering.swift
> +  {
```suggestion
  func llvm(
    boundGenericType val: BoundGenericType, in module: inout SwiftyLLVM.Module
  ) -> SwiftyLLVM.IRType {
```

2024-03-28 07:28 UTC, kyouko-taiga commented on Sources/Core/AST/Stmt/ConditionalCompilationStmt.swift
> +    case or(Condition, SequenceCondition)
```suggestion
  public indirect enum SequenceCondition: Codable {

    case operand(Condition)

    case and(Condition, SequenceCondition)

    case or(Condition, SequenceCondition)
```

We add spaces after/before the opening/closing braces of types and we add spaces between member declarations. The same rule should be applied to the lines below.

2024-03-28 07:30 UTC, kyouko-taiga commented on Sources/Core/AST/Stmt/ConditionalCompilationStmt.swift
> +    {
```suggestion
    private func unroll(
      for factors: ConditionalCompilationFactors, conditionCase: ConditionKind
    ) -> Bool {
```

We avoid using abbreviations in code and prefer `conditionCase` (which I guess is what you meant here) over `condCase`. The fact that I had to guess is precisely the reason why we stay away from a abbreviations.

2024-03-28 07:31 UTC, kyouko-taiga commented on Sources/Core/AST/Stmt/ConditionalCompilationStmt.swift
> +    {
Looking at use sites, I suspect using simply `condition` would be a better name.

2024-03-28 07:31 UTC, kyouko-taiga commented on Sources/Core/AST/Stmt/ConditionalCompilationStmt.swift
> +      case .or(let cond, let seq):
```suggestion

      case .or(let cond, let seq):
```

I would add a newline here for legibility.

2024-03-28 07:34 UTC, kyouko-taiga commented on Sources/Core/AST/Stmt/ConditionalCompilationStmt.swift
> +    /// Visit the SequenceCondition tail to calculate the right case for executing the right branch
Why not define this abstraction as a tree? We have `SequenceExpr` because the precedence and associativity of operators occurring in expressions in not known during parsing. But I don't think we want to support custom operators in conditional compilation statements. If we only have `||` and `&&`, then we can parse any expression directly into a tree rather than having to post-process a sequence.

2024-03-28 07:36 UTC, kyouko-taiga commented on Sources/Core/AST/Stmt/ConditionalCompilationStmt.swift
> +  /// A sequence of structured conditions to elaborate a 1 to N operand compilation condition
Why not define this abstraction as a tree? We have SequenceExpr because the precedence and associativity of operators occurring in expressions in not known during parsing. But I don't think we want to support custom operators in conditional compilation statements. If we only have || and &&, then we can parse any expression directly into a tree rather than having to post-process a sequence.

2024-03-28 07:37 UTC, kyouko-taiga commented on Sources/Core/AST/Stmt/ConditionalCompilationStmt.swift
> +    }
Please document these functions. Also do they really need to be `public`?

2024-03-28 07:39 UTC, kyouko-taiga commented on Sources/Core/AST/Stmt/ConditionalCompilationStmt.swift
> +    condition.allHolds(for: factors) ? stmts : fallback
I don't think the change reads well. `condition.holds` is best, _even_ if `condition` must be described has a sequence. As your documentation specifies:

> A sequence of structured conditions to elaborate a 1 to N operand compilation condition

So, really, `condition` notionally describes a single condition that may or may not be composed of multiple conditions.

2024-03-28 07:41 UTC, kyouko-taiga commented on Sources/FrontEnd/Parse/Parser.swift
> +  private static func buildSequenceCondition(
You can use [precedence climbing](https://en.wikipedia.org/wiki/Operator-precedence_parser#Precedence_climbing_method) to parse a tree directly. Since we only care about `||` and `&&` we can now at parsing how to apply precedence.

2024-03-28 07:42 UTC, kyouko-taiga commented on Sources/FrontEnd/Parse/Parser.swift
> +    let conditionSeq = try buildSequenceCondition(in: &state)
Please avoid using abbreviations and suffixing variables by their type.
```suggestion
    let conditions = try buildSequenceCondition(in: &state)
```

2024-03-28 07:43 UTC, kyouko-taiga commented on Sources/GenerateHyloFileTests/GenerateHyloFileTests.swift
> +        """
Were those extra spaces added by swift-format?

2024-03-28 07:46 UTC, kyouko-taiga requested changes
Thanks a lot for this PR!

I left a handful of inline comments. The most important one is that I think `SequenceCondition` should be defined as a tree rather than a sequence, and its API should not unnecessary leak details about its internal representation. Specifically, users of the abstraction typically do not care whether it is represented as a sequence, a tree, or any other data structure. For all intents and purposes, it's just a condition.

Other comments are about styling issue.

2024-03-28 16:58 UTC, Metalymph commented on Sources/GenerateHyloFileTests/GenerateHyloFileTests.swift
> +        """
Yes

2024-03-30 12:39 UTC, Metalymph commented
Thanks a lot for your kind review! 

I've just updated it

2024-03-30 13:12 UTC, kyouko-taiga commented on Sources/Core/AST/Stmt/ConditionalCompilationStmt.swift
> +  /// Abstracts the whole condition structure and its sub-conditions.
I think there is a way to improve this docs.
```suggestion
  /// A condition in a conditional compilation statement expressed as a composition of predicates.
```
But at the same time it occurred to me that we could probably modify `Condition` rather than introducing a new abstraction. That's because the most natural way to document this thing is to say that a condition is a propositional statement (as in propositional logic). The propositions are the factors.

2024-03-30 13:13 UTC, kyouko-taiga commented on Sources/Core/AST/Stmt/ConditionalCompilationStmt.swift
> +    case operand(Condition)
```suggestion
    /// A proposition or the negation of a proposition.
    case operand(Condition)
```

2024-03-30 13:13 UTC, kyouko-taiga commented on Sources/Core/AST/Stmt/ConditionalCompilationStmt.swift
> +    case and(ConditionTree, ConditionTree)
```suggestion
    /// A conjunction of conditions.
    case and(ConditionTree, ConditionTree)
```

2024-03-30 13:13 UTC, kyouko-taiga commented on Sources/Core/AST/Stmt/ConditionalCompilationStmt.swift
> +    case or(ConditionTree, ConditionTree)
```suggestion
    /// A disjunction of conditions.
    case or(ConditionTree, ConditionTree)
```

2024-03-30 13:14 UTC, kyouko-taiga commented on Sources/Core/AST/Stmt/ConditionalCompilationStmt.swift
> +    }
```suggestion
    public enum ConditionKind: String {

      case holdOnly

      case skipMain

      case skipElse

    }
```
I'm not sure to understand what this abstraction is representing. Having docs would help.

2024-03-30 13:15 UTC, kyouko-taiga commented on Sources/Core/AST/Stmt/ConditionalCompilationStmt.swift
> +    /// Visit the SequenceCondition tail to calculate the right case for executing the right branch.
```suggestion
    /// Visits the SequenceCondition tail to calculate the right case for executing the right branch.
```
Please document what `conditionCase` mean for this function.

2024-03-30 13:15 UTC, kyouko-taiga commented on Sources/Core/AST/Stmt/ConditionalCompilationStmt.swift
> +    /// Return `true` iff the the full condition is satisfied.
```suggestion
    /// Returns `true` iff the the condition is satisfied.
```
I don't think we ever care about a condition being partially satisfied.

2024-03-30 13:16 UTC, kyouko-taiga commented on Sources/Core/AST/Stmt/ConditionalCompilationStmt.swift
> +    /// Return `true` iff the the full condition is unsatisfied.
```suggestion
    /// Returns `true` iff the condition is not unsatisfied.
```

2024-03-30 13:17 UTC, kyouko-taiga commented on Sources/Core/AST/Stmt/ConditionalCompilationStmt.swift
> +    /// Return `true` iff the the full condition is satisfied.
```suggestion
    /// Returns `true` iff the the condition is satisfied.
```
What is the difference between `mustSkipMainBranch(for:)` and `holds(for:)`?

2024-03-30 13:18 UTC, kyouko-taiga commented on Sources/Core/BuiltinFunction.swift
> +{
```suggestion
private func overflowBehavior(
  _ stream: inout ArraySlice<Substring>
) -> SwiftyLLVM.OverflowBehavior {
```

2024-03-30 13:19 UTC, kyouko-taiga commented on Sources/FrontEnd/Parse/Parser.swift
> +    /// Calculates operator's precedence.
```suggestion
    /// Returns the precedence of `tokenValue`, which is a either `||` or `&&`.
```

2024-03-30 13:21 UTC, kyouko-taiga commented on Sources/FrontEnd/Parse/Parser.swift
> +      default: -1
Do not use `-1` to represent invalid domains. Document your precondition and use `preconditionFailure` or `precondition` to make sure they hold in your function.

But also I suspect there is a type-safer way to write this method. Why do we have to use string input?

2024-03-30 13:24 UTC, kyouko-taiga commented on Sources/FrontEnd/Parse/Parser.swift
> +        let tokenValue = state.token(op).value
Here I think you could translate the token that you parsed into an enum instance representing possible operators (rather than a string) and then use a safer API for `precedence(_:)`.

2024-03-30 13:27 UTC, kyouko-taiga commented on Sources/FrontEnd/Parse/Parser.swift
> +        backup = state.backup()
Do we really need to backup all the way? I guess it should be fine to exit the first time you encounter an operator with the wrong precedence.

2024-03-30 13:58 UTC, Metalymph commented on Sources/Core/AST/Stmt/ConditionalCompilationStmt.swift
> +    /// Return `true` iff the the full condition is satisfied.
Originally I wanted to separated the intents to make more clear the proper action. On this of course I can also remove the 3 specific functions and directly use `unroll` and renaming the latter as `visitWithConditionKind`

2024-03-31 08:47 UTC, kyouko-taiga commented
FYI, here's what I mean when I say that we can represent the conjunctions and disjunctions without introducing a new abstraction: https://github.com/hylo-lang/hylo/commit/bc65aac5fb181e16bade3825fbd7c92eda81c150

2024-03-31 10:09 UTC, Metalymph commented
> FYI, here's what I mean when I say that we can represent the conjunctions and disjunctions without introducing a new abstraction: [bc65aac](https://github.com/hylo-lang/hylo/commit/bc65aac5fb181e16bade3825fbd7c92eda81c150)

Ok, so you've just embedded it inside the `ConditionalCompilerStmt`. The abstraction could have been avoiding indeed, I was wrong. Thanks

2024-06-13 16:27 UTC, Metalymph commented
> @Metalymph this looks like valuable work. Do you think we can move this PR forward and get it merged soon so the value isn't lost?

Hi @dabrahams and thanks a lot to remember me about this. Essentially the correct version of this issue is been rewritten on https://github.com/hylo-lang/hylo/compare/Mtalymph-1410 by @kyouko-taiga. So this one could be also redirected and closed if there's no additional work to do on it.

2024-06-14 22:38 UTC, dabrahams commented
@kyouko-taiga I'm sorry I don't understand what @Metalymph is saying.  Perhaps you know how to sort this out?

2024-06-15 10:50 UTC, kyouko-taiga commented
I don't remember exactly but I think I opened a branch to illustrate the changes I envisioned and that's what's been linked. If @Metalymph can confirm I think we should close this PR and I can take care of pushing my branch through the finish line.

2024-06-15 11:03 UTC, Metalymph commented
> I don't remember exactly but I think I opened a branch to illustrate the changes I envisioned and that's what's been linked. If @Metalymph can confirm I think we should close this PR and I can take care of pushing my branch through the finish line.

Yes, Thanks!

2024-06-16 07:44 UTC, closed without merging