Add atomics support in the standard library
hylo-lang/hylo pull request #1637
Opened 2024-12-20 20:38 UTC by lucteo

2025-01-03 18:42 UTC, lucteo commented
@kyouko-taiga : Do you have any idea why I get a "Sources/FrontEnd/TypeChecking/TypeChecker.swift:6183: Assertion failed: type already inferred" error on many of the tests on Ubuntu builds (see https://github.com/hylo-lang/hylo/actions/runs/12597537109/job/35110729555?pr=1637)?

2025-01-09 09:17 UTC, kyouko-taiga commented
> @kyouko-taiga : Do you have any idea why I get a "Sources/FrontEnd/TypeChecking/TypeChecker.swift:6183: Assertion failed: type already inferred" error on many of the tests on Ubuntu builds (see https://github.com/hylo-lang/hylo/actions/runs/12597537109/job/35110729555?pr=1637)?

It means something causes the type checker to visit the same tree twice. If you point me at the test cases that are failing I can investigate if you want.

2025-01-09 19:21 UTC, lucteo commented
The failures can be seen at https://github.com/hylo-lang/hylo/actions/runs/12597537109/job/35110729555?pr=1637.
It shows me the following failed tests:
```
	  2 - DriverTests (ILLEGAL)
	  3 - ManglingTests (ILLEGAL)
	  4 - HyloTests (ILLEGAL)
	  5 - HyloTests_TestCases_Lowering_0 (ILLEGAL)
	  6 - HyloTests_TestCases_Lowering_1 (ILLEGAL)
	  7 - HyloTests_TestCases_Lowering_2 (ILLEGAL)
	  8 - HyloTests_TestCases_Lowering_3 (ILLEGAL)
	  9 - HyloTests_TestCases_Parsing_0 (ILLEGAL)
	 10 - HyloTests_TestCases_Parsing_1 (ILLEGAL)
	 11 - HyloTests_TestCases_Parsing_2 (ILLEGAL)
	 12 - HyloTests_TestCases_TypeChecking_0 (ILLEGAL)
	 13 - HyloTests_TestCases_TypeChecking_1 (ILLEGAL)
	 14 - HyloTests_TestCases_TypeChecking_2 (ILLEGAL)
	 15 - HyloTests_TestCases_TypeChecking_3 (ILLEGAL)
	 16 - HyloTests_TestCases_TypeChecking_4 (ILLEGAL)
	 17 - HyloTests_TestCases_TypeChecking_5 (ILLEGAL)
	 18 - HyloTests_TestCases_TypeChecking_6 (ILLEGAL)
	 19 - HyloTests_TestCases_TypeChecking_7 (ILLEGAL)
	 20 - HyloTests_TestCases_TypeChecking_8 (ILLEGAL)
	 21 - HyloTests_TestCases_TypeChecking_9 (ILLEGAL)
	 22 - HyloTests_TestCases_TypeChecking_10 (ILLEGAL)
	 23 - EndToEndTests (ILLEGAL)
	 24 - EndToEndTests_TestCases_0 (ILLEGAL)
	 25 - EndToEndTests_TestCases_1 (ILLEGAL)
	 26 - EndToEndTests_TestCases_2 (ILLEGAL)
	 27 - EndToEndTests_TestCases_3 (ILLEGAL)
	 28 - EndToEndTests_TestCases_4 (ILLEGAL)
	 29 - EndToEndTests_TestCases_Concurrency (ILLEGAL)
	 31 - LibraryTests_TestCases_0 (ILLEGAL)
	 32 - LibraryTests_TestCases_1 (ILLEGAL)
```

Please note that these tests only fail on Ubuntul, I haven't seen any failures on MacOS.

2025-01-14 06:07 UTC, kyouko-taiga commented
If the failure is so widespread I think there's something going wrong with your code generator. It's surprising that the error occurs only on Ubuntu but perhaps that's because you're generating a duplicate declaration only on this platform?

My current theory is that two identical definitions are being fed to the type checker (which currently does not check for duplicate declaration).

2025-03-11 15:51 UTC, kyouko-taiga commented on StandardLibrary/Sources/LowLevel/Threading/AtomicRepresentable.hylo
> +  type AtomicRepresentation: PlatformAtomic;
```suggestion
  type AtomicRepresentation: PlatformAtomic
```

2025-03-11 16:06 UTC, kyouko-taiga requested changes
Nice work. See inline comments.

2025-03-11 16:06 UTC, kyouko-taiga commented on StandardLibrary/Sources/LowLevel/Threading/Atomic.hylo
> +  /// Atomically updates `this` by adding `value` to it, using `ordering`, and return the original value.
```suggestion
  /// Atomically updates `self` by adding `value` to it, using `ordering`, and return the original value.
```

Also you used "the atomic" in other comments. It would be best if we can have consistent docs.

2025-03-11 16:06 UTC, kyouko-taiga commented on StandardLibrary/Sources/LowLevel/Threading/PlatformAtomic.hylo
> +trait IntegerPlatformAtomic: PlatformAtomic {
I don't understand the trait hierarchy that's being defined and I'm under the impression that it may be simplified. Some documentation would help me understand the intent and see whether I'm wrong.

2025-03-11 16:06 UTC, kyouko-taiga commented on StandardLibrary/Sources/LowLevel/Threading/PlatformAtomics.hylo
> +// MARK: Int8PlatformAtomic
A specific reason why all these types are declared in a single file? The usual approach has been to declare one type per file so far. Although it is not a strict convention I'd like to understand why it is not followed here.

2025-03-11 21:00 UTC, lucteo commented on StandardLibrary/Sources/LowLevel/Threading/PlatformAtomic.hylo
> +trait IntegerPlatformAtomic: PlatformAtomic {
I'll try to simplify it.

2025-03-12 19:07 UTC, lucteo commented on StandardLibrary/Sources/LowLevel/Threading/PlatformAtomics.hylo
> +public type IntPlatformAtomic: Regular {
I remember now the reason for this choice. I don't want to expose the atomic functions on types like `Int`, `Int32`, etc. This is why, these primitives are hidden behind other types.

2026-05-20 18:28 UTC, closed without merging